### 随机端口
server:
  port: 0
spring:
  application:
    name: zk-discovery-client
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
### 监控配置
management:
  server:
    port: 8086
  endpoints:
    web:
      exposure:
        include: '*'
